-- ----------------------------
-- Table structure for sys_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_user";
CREATE TABLE "public"."sys_user" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
),
  "username" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "real_name" varchar(50) COLLATE "pg_catalog"."default",
  "avatar" varchar(255) COLLATE "pg_catalog"."default",
  "desc" varchar(255) COLLATE "pg_catalog"."default",
  "status" varchar(20) COLLATE "pg_catalog"."default" DEFAULT 'normal'::character varying,
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "sys_user_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "sys_user_username_key" UNIQUE ("username")
)
;

COMMENT ON TABLE "public"."sys_user" IS '系统用户表';
COMMENT ON COLUMN "public"."sys_user"."id" IS '用户ID';
COMMENT ON COLUMN "public"."sys_user"."username" IS '用户名';
COMMENT ON COLUMN "public"."sys_user"."password" IS '密码';
COMMENT ON COLUMN "public"."sys_user"."real_name" IS '真实姓名';
COMMENT ON COLUMN "public"."sys_user"."avatar" IS '头像地址';
COMMENT ON COLUMN "public"."sys_user"."desc" IS '描述';
COMMENT ON COLUMN "public"."sys_user"."status" IS '状态: normal-正常, locked-锁定';
COMMENT ON COLUMN "public"."sys_user"."created_at" IS '创建时间';

-- ----------------------------
-- Records of sys_user
-- ----------------------------
INSERT INTO "public"."sys_user" ("username", "password", "real_name", "desc", "status") VALUES ('admin', '123456', 'Admin', 'Super Administrator', 'normal');

-- ----------------------------
-- Table structure for sys_role
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_role";
CREATE TABLE "public"."sys_role" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
),
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "value" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "explain" varchar(255) COLLATE "pg_catalog"."default",
  "is_default" bool DEFAULT false,
  "status" varchar(20) COLLATE "pg_catalog"."default" DEFAULT 'normal'::character varying,
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "sys_role_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "sys_role_name_key" UNIQUE ("name"),
  CONSTRAINT "sys_role_value_key" UNIQUE ("value")
)
;

COMMENT ON TABLE "public"."sys_role" IS '系统角色表';
COMMENT ON COLUMN "public"."sys_role"."id" IS '角色ID';
COMMENT ON COLUMN "public"."sys_role"."name" IS '角色名称';
COMMENT ON COLUMN "public"."sys_role"."value" IS '角色值';
COMMENT ON COLUMN "public"."sys_role"."explain" IS '说明';
COMMENT ON COLUMN "public"."sys_role"."is_default" IS '是否默认角色';
COMMENT ON COLUMN "public"."sys_role"."status" IS '状态';

-- ----------------------------
-- Records of sys_role
-- ----------------------------
INSERT INTO "public"."sys_role" ("name", "value", "explain", "is_default") VALUES ('Super Admin', 'super_admin', 'Has all permissions', 'f');
INSERT INTO "public"."sys_role" ("name", "value", "explain", "is_default") VALUES ('Ordinary User', 'user', 'Standard access', 't');

-- ----------------------------
-- Table structure for sys_menu
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_menu";
CREATE TABLE "public"."sys_menu" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
),
  "parent_id" int8,
  "label" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "menu_key" varchar(100) COLLATE "pg_catalog"."default",
  "type" int4 NOT NULL,
  "subtitle" varchar(100) COLLATE "pg_catalog"."default",
  "open_type" int4 DEFAULT 1,
  "auth" varchar(255) COLLATE "pg_catalog"."default",
  "path" varchar(255) COLLATE "pg_catalog"."default",
  "icon" varchar(100) COLLATE "pg_catalog"."default",
  "is_hidden" bool DEFAULT false,
  "sort_order" int4 DEFAULT 0,
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "sys_menu_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "sys_menu_key_key" UNIQUE ("menu_key")
)
;

COMMENT ON TABLE "public"."sys_menu" IS '系统菜单表';
COMMENT ON COLUMN "public"."sys_menu"."id" IS '菜单ID';
COMMENT ON COLUMN "public"."sys_menu"."parent_id" IS '父菜单ID';
COMMENT ON COLUMN "public"."sys_menu"."label" IS '菜单名称';
COMMENT ON COLUMN "public"."sys_menu"."menu_key" IS '菜单标识';
COMMENT ON COLUMN "public"."sys_menu"."type" IS '类型: 1-菜单, 2-按钮';
COMMENT ON COLUMN "public"."sys_menu"."subtitle" IS '子标题';
COMMENT ON COLUMN "public"."sys_menu"."open_type" IS '打开方式: 1-内部, 2-外部';
COMMENT ON COLUMN "public"."sys_menu"."auth" IS '权限标识';
COMMENT ON COLUMN "public"."sys_menu"."path" IS '路由路径';
COMMENT ON COLUMN "public"."sys_menu"."icon" IS '图标';
COMMENT ON COLUMN "public"."sys_menu"."is_hidden" IS '是否隐藏: true-隐藏, false-显示';
COMMENT ON COLUMN "public"."sys_menu"."sort_order" IS '排序';

-- ----------------------------
-- Records of sys_menu
-- ----------------------------
INSERT INTO "public"."sys_menu" ("id", "parent_id", "label", "menu_key", "type", "subtitle", "open_type", "auth", "path", "sort_order", "is_hidden") VALUES (1, NULL, 'Dashboard', 'dashboard', 1, 'dashboard', 1, 'dashboard', '/dashboard', 1, false);
INSERT INTO "public"."sys_menu" ("id", "parent_id", "label", "menu_key", "type", "subtitle", "open_type", "auth", "path", "sort_order", "is_hidden") VALUES (2, 1, '主控台', 'console', 1, 'console', 1, 'console', '/dashboard/console', 1, false);
INSERT INTO "public"."sys_menu" ("id", "parent_id", "label", "menu_key", "type", "subtitle", "open_type", "auth", "path", "sort_order", "is_hidden") VALUES (3, 1, '工作台', 'workplace', 1, 'workplace', 1, 'workplace', '/dashboard/workplace', 2, false);
INSERT INTO "public"."sys_menu" ("id", "parent_id", "label", "menu_key", "type", "subtitle", "open_type", "auth", "path", "sort_order", "is_hidden") VALUES (4, NULL, '表单管理', 'form', 1, 'form', 1, 'form', '/form', 2, false);
INSERT INTO "public"."sys_menu" ("id", "parent_id", "label", "menu_key", "type", "subtitle", "open_type", "auth", "path", "sort_order", "is_hidden") VALUES (5, 4, '基础表单', 'basic-form', 1, 'basic-form', 1, 'basic-form', '/form/basic-form', 1, false);
INSERT INTO "public"."sys_menu" ("id", "parent_id", "label", "menu_key", "type", "subtitle", "open_type", "auth", "path", "sort_order", "is_hidden") VALUES (6, 4, '分步表单', 'step-form', 1, 'step-form', 1, 'step-form', '/form/step-form', 2, false);
INSERT INTO "public"."sys_menu" ("id", "parent_id", "label", "menu_key", "type", "subtitle", "open_type", "auth", "path", "sort_order", "is_hidden") VALUES (7, 4, '表单详情', 'detail', 1, 'detail', 1, 'detail', '/form/detail', 3, false);

-- ----------------------------
-- Table structure for sys_user_role
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_user_role";
CREATE TABLE "public"."sys_user_role" (
  "user_id" int8 NOT NULL,
  "role_id" int8 NOT NULL,
  CONSTRAINT "sys_user_role_pkey" PRIMARY KEY ("user_id", "role_id"),
  CONSTRAINT "fk_sys_user_role_user" FOREIGN KEY ("user_id") REFERENCES "public"."sys_user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "fk_sys_user_role_role" FOREIGN KEY ("role_id") REFERENCES "public"."sys_role" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)
;

COMMENT ON TABLE "public"."sys_user_role" IS '用户角色关联表';

-- ----------------------------
-- Records of sys_user_role
-- ----------------------------
INSERT INTO "public"."sys_user_role" ("user_id", "role_id") VALUES (1, 1);

-- ----------------------------
-- Table structure for sys_role_menu
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_role_menu";
CREATE TABLE "public"."sys_role_menu" (
  "role_id" int8 NOT NULL,
  "menu_id" int8 NOT NULL,
  CONSTRAINT "sys_role_menu_pkey" PRIMARY KEY ("role_id", "menu_id"),
  CONSTRAINT "fk_sys_role_menu_role" FOREIGN KEY ("role_id") REFERENCES "public"."sys_role" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "fk_sys_role_menu_menu" FOREIGN KEY ("menu_id") REFERENCES "public"."sys_menu" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)
;

COMMENT ON TABLE "public"."sys_role_menu" IS '角色菜单关联表';

-- ----------------------------
-- Records of sys_role_menu
-- ----------------------------
INSERT INTO "public"."sys_role_menu" ("role_id", "menu_id") VALUES (1, 1);
INSERT INTO "public"."sys_role_menu" ("role_id", "menu_id") VALUES (1, 2);
INSERT INTO "public"."sys_role_menu" ("role_id", "menu_id") VALUES (1, 3);
INSERT INTO "public"."sys_role_menu" ("role_id", "menu_id") VALUES (1, 4);
INSERT INTO "public"."sys_role_menu" ("role_id", "menu_id") VALUES (1, 5);
INSERT INTO "public"."sys_role_menu" ("role_id", "menu_id") VALUES (1, 6);
INSERT INTO "public"."sys_role_menu" ("role_id", "menu_id") VALUES (1, 7);
